apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nodejs
  namespace: app-front
  labels:
    app: api-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nodejs
  template:
    metadata:
      labels:
        app: api-nodejs
    spec:
      containers:
      - name: app-api
        image: node/api-server:1.0
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Service
metadata:
  name: api-nodejs
  namespace: app-front
spec:
  selector:
    app: api-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer